from selenium import webdriver
driver = webdriver.Firefox()
driver.get("file:///C:/Users/pgandhi/Documents/Selenium/Ex_Files_Python_Automation_Testing/Ex_Files_Python_Automation_Testing/Exercise%20Files/CH02/html_code_02.html")
login_form_absolute = driver.find_element_by_xpath('/html/body[1]')
login_form_relative = driver.find_element_by_xpath('//form[1]')
login_form_id = driver.find_element_by_xpath('//form[@id="loginForm"]')
print("My loginf form element is: ")
print(login_form_absolute)
print(login_form_relative)
print(login_form_id)
driver.close()
